---
title-block-banner: fiveoone_banner.png
title-block-banner-color: light
titlegraphic: fiveoone_banner.png
sidebar: false

listing:
  id: lessons
  categories: unnumbered
  contents:
    - Lesson0.qmd
    - Lesson01.qmd
    - Lesson02.qmd
    - Lesson03.qmd
    - Lesson04.qmd
    - Lesson05.qmd
    - Lesson06.qmd
    - Lesson07.qmd
    - Lesson08.qmd
    - Lesson09.qmd
    - Lesson10.qmd
    - Lesson11.qmd
    - Lesson12.qmd

  type: grid
  grid-columns: 4
  grid-item-align: center
  fields: [image,title, categories, file-modified]
  field-display-names: 
    title: "Lessons"
    file-modified: "Updated:"
  date-format: short
  sort: "filename"
---

## About this course {.unnumbered}

Welcome to the course notes for STAT 501: Regression Methods. These notes are designed and developed by [Penn State's Department of Statistics](https://science.psu.edu/stat) and offered as open educational resources. These notes are free to use under Creative Commons license [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).

This course is part of the Online Master of Applied Statistics program offered by Penn State's World Campus.

<center>
<a href="https://www.worldcampus.psu.edu/register-or-schedule-courses" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Ready to enroll?</a>
</center>

::: {.border-start .border-success .ms-3 .ps-2 }
### Currently enrolled?

If you are a current student in this course, please see [Canvas](https://psu.instructure.com/) for your syllabus, assignments, lesson videos, and communication from your instructor.
:::

## Lessons

::: {#lessons}
:::

### Contributors

This is the STAT 501 online course materials website. There are lots of examples, notes, and lecture materials on this website. You may want to make a bookmark for this site in your browser.

Featured on this site are the online notes on Regression Methods reorganized and supplemented by Dr. Iain Pardoe, based on original notes by Dr. Laura Simon and Dr. Derek Young.

In addition, in the resources section, there are worked examples using Minitab that demonstrate how to perform many of the methods used in regression and video resources containing instructive examples.
